title: Shuvam Shah # The title of the blog
author: Shuvam Shah # Your name 
email: shuvamkshah28@gmail.com # your email shown in the footer
url: https://shvms.github.io/ # this is your site's root address.
description: > # this means to ignore newlines until "show_excerpts:"
  A blog
favicon: "./favicon.ico" # set the favicon of the site 

show_excerpts: false # set to true to show excerpts on the homepage
  
# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  avatar_url: "https://lh3.googleusercontent.com/ghZGpWh__F-d4r7fKBFmC755yjx_giNk66NFq8VYTDA7o2rAQOiTDWKOOhroTaimgwKcglnnPWpu2bEswOy49E3Sj9O196mxkJAdM_xTzeic4wL3nlvkCvMQSe-QgltHW8mFoLfzGw=w1200" # avatar in about page
  about_you: sophomore at jadavpur university - dept. of it # short description about you in about page
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

  # generate social links in about page.
  social_links:
    twitter: shahshuvam
    github:  shvms
    # rss: RSS
    # dribbble: 
    facebook: shvms10
    # flickr:   
    instagram: u_1f623
    linkedin: shuvam-shah-b6651219b
    # pinterest: 
    # youtube: 
    # youtube_channel: 
    # youtube_channel_name: 
    # telegram: 
    # googleplus: 
    # microdotblog: 
    # reddit: 

    # Mastodon instances
    # mastodon:
    # - username: 
    #   instance: 
    # - username: 
    #   instance: 

# Build settings
remote_theme: huangyz0918/moving # note, please use huangyz0918/moving if you want to publish to Github Pages.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  # - spotify-player